//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniTrack.Application.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniTrack.Application.Common.Localization.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked in to this event..
        /// </summary>
        internal static string AlreadyCheckedIn {
            get {
                return ResourceManager.GetString("AlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already commented on this event..
        /// </summary>
        internal static string AlreadyCommented {
            get {
                return ResourceManager.GetString("AlreadyCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already following this club.
        /// </summary>
        internal static string AlreadyFollowingClub {
            get {
                return ResourceManager.GetString("AlreadyFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already joined this event.
        /// </summary>
        internal static string AlreadyJoinedEvent {
            get {
                return ResourceManager.GetString("AlreadyJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already liked this comment..
        /// </summary>
        internal static string AlreadyLiked {
            get {
                return ResourceManager.GetString("AlreadyLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully checked in to the event..
        /// </summary>
        internal static string CheckInSuccess {
            get {
                return ResourceManager.GetString("CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club is created successes..
        /// </summary>
        internal static string ClubCreatedSuccess {
            get {
                return ResourceManager.GetString("ClubCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use.
        /// </summary>
        internal static string ClubEmailAlreadyExists {
            get {
                return ResourceManager.GetString("ClubEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clubs found..
        /// </summary>
        internal static string ClubFansNotFound {
            get {
                return ResourceManager.GetString("ClubFansNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club is not found..
        /// </summary>
        internal static string ClubNotFound {
            get {
                return ResourceManager.GetString("ClubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No club found with this email address..
        /// </summary>
        internal static string ClubNotFoundByEmail {
            get {
                return ResourceManager.GetString("ClubNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club password has been updated successfully..
        /// </summary>
        internal static string ClubPasswordResetSuccess {
            get {
                return ResourceManager.GetString("ClubPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during club registration.
        /// </summary>
        internal static string ClubRegisterFailed {
            get {
                return ResourceManager.GetString("ClubRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid club tag.
        /// </summary>
        internal static string ClubTagInvalid {
            get {
                return ResourceManager.GetString("ClubTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team created successfully..
        /// </summary>
        internal static string ClubTeamCreatedSuccess {
            get {
                return ResourceManager.GetString("ClubTeamCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team deleted successfully..
        /// </summary>
        internal static string ClubTeamDeletedSuccess {
            get {
                return ResourceManager.GetString("ClubTeamDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team not found or you are not authorized to delete it..
        /// </summary>
        internal static string ClubTeamNotFound {
            get {
                return ResourceManager.GetString("ClubTeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club has been successfully verified..
        /// </summary>
        internal static string ClubVerifiedSuccess {
            get {
                return ResourceManager.GetString("ClubVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment added successfully..
        /// </summary>
        internal static string CommentCreatedSuccess {
            get {
                return ResourceManager.GetString("CommentCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment deleted successfully..
        /// </summary>
        internal static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment not found..
        /// </summary>
        internal static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully. We will get back to you as soon as possible..
        /// </summary>
        internal static string ContactMessageSent {
            get {
                return ResourceManager.GetString("ContactMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new event..
        /// </summary>
        internal static string CreatedNewEvent {
            get {
                return ResourceManager.GetString("CreatedNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A department with this name already exists..
        /// </summary>
        internal static string DepartmentAlreadyExists {
            get {
                return ResourceManager.GetString("DepartmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department created successfully..
        /// </summary>
        internal static string DepartmentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is deleted successfully..
        /// </summary>
        internal static string DepartmentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department not found..
        /// </summary>
        internal static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use.
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        internal static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event city is required..
        /// </summary>
        internal static string EventCityRequired {
            get {
                return ResourceManager.GetString("EventCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time/clock is required..
        /// </summary>
        internal static string EventClockRequired {
            get {
                return ResourceManager.GetString("EventClockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event club is required..
        /// </summary>
        internal static string EventClubRequired {
            get {
                return ResourceManager.GetString("EventClubRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new event has been created..
        /// </summary>
        internal static string EventCreatedNotification {
            get {
                return ResourceManager.GetString("EventCreatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event created successfully..
        /// </summary>
        internal static string EventCreatedSuccess {
            get {
                return ResourceManager.GetString("EventCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; event has been deleted..
        /// </summary>
        internal static string EventDeletedNotification {
            get {
                return ResourceManager.GetString("EventDeletedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully..
        /// </summary>
        internal static string EventDeletedSuccess {
            get {
                return ResourceManager.GetString("EventDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description is required..
        /// </summary>
        internal static string EventDescriptionRequired {
            get {
                return ResourceManager.GetString("EventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after the start date..
        /// </summary>
        internal static string EventEndDateInvalid {
            get {
                return ResourceManager.GetString("EventEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event has already ended.
        /// </summary>
        internal static string EventExpired {
            get {
                return ResourceManager.GetString("EventExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required for deletion..
        /// </summary>
        internal static string EventIdRequired {
            get {
                return ResourceManager.GetString("EventIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is deleted..
        /// </summary>
        internal static string EventIsDeleted {
            get {
                return ResourceManager.GetString("EventIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is updated.
        /// </summary>
        internal static string EventIsUpdated {
            get {
                return ResourceManager.GetString("EventIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully joined the event.
        /// </summary>
        internal static string EventJoinSuccess {
            get {
                return ResourceManager.GetString("EventJoinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully left the event.
        /// </summary>
        internal static string EventLeftSuccess {
            get {
                return ResourceManager.GetString("EventLeftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event location is required..
        /// </summary>
        internal static string EventLocationRequired {
            get {
                return ResourceManager.GetString("EventLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has not ended yet..
        /// </summary>
        internal static string EventNotFinished {
            get {
                return ResourceManager.GetString("EventNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were made to the event.
        /// </summary>
        internal static string EventNotModified {
            get {
                return ResourceManager.GetString("EventNotModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event quota is full.
        /// </summary>
        internal static string EventQuotaFull {
            get {
                return ResourceManager.GetString("EventQuotaFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event quota must be a positive number..
        /// </summary>
        internal static string EventQuotaInvalid {
            get {
                return ResourceManager.GetString("EventQuotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be in the past or invalid..
        /// </summary>
        internal static string EventStartDateInvalid {
            get {
                return ResourceManager.GetString("EventStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event status provided..
        /// </summary>
        internal static string EventStatusInvalid {
            get {
                return ResourceManager.GetString("EventStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one valid event tag is required..
        /// </summary>
        internal static string EventTagInvalid {
            get {
                return ResourceManager.GetString("EventTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title is required..
        /// </summary>
        internal static string EventTitleRequired {
            get {
                return ResourceManager.GetString("EventTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is only available to students of the same university.
        /// </summary>
        internal static string EventUniversityOnly {
            get {
                return ResourceManager.GetString("EventUniversityOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event university is required..
        /// </summary>
        internal static string EventUniversityRequired {
            get {
                return ResourceManager.GetString("EventUniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &apos;{0}&apos; you joined has been updated..
        /// </summary>
        internal static string EventUpdatedNotification {
            get {
                return ResourceManager.GetString("EventUpdatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated successfully..
        /// </summary>
        internal static string EventUpdatedSuccess {
            get {
                return ResourceManager.GetString("EventUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club followed successfully.
        /// </summary>
        internal static string FollowClubSuccess {
            get {
                return ResourceManager.GetString("FollowClubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event loaded successfully..
        /// </summary>
        internal static string GetEventSuccesses {
            get {
                return ResourceManager.GetString("GetEventSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event’s Google Sheets spreadsheet ID could not be found..
        /// </summary>
        internal static string GoogleSheetsTableNotFound {
            get {
                return ResourceManager.GetString("GoogleSheetsTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid or has expired..
        /// </summary>
        internal static string InvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("InvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tag selection.
        /// </summary>
        internal static string InvalidTag {
            get {
                return ResourceManager.GetString("InvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at most 100 characters..
        /// </summary>
        internal static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 2 characters..
        /// </summary>
        internal static string MinLength2 {
            get {
                return ResourceManager.GetString("MinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not following this club.
        /// </summary>
        internal static string NotFollowingClub {
            get {
                return ResourceManager.GetString("NotFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are already closed for this club..
        /// </summary>
        internal static string NotificationAlreadyClosed {
            get {
                return ResourceManager.GetString("NotificationAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are already enabled for this club..
        /// </summary>
        internal static string NotificationAlreadyOpened {
            get {
                return ResourceManager.GetString("NotificationAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club notifications have been successfully closed..
        /// </summary>
        internal static string NotificationClosedSuccess {
            get {
                return ResourceManager.GetString("NotificationClosedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification not found.
        /// </summary>
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club notifications have been successfully enabled..
        /// </summary>
        internal static string NotificationOpenedSuccess {
            get {
                return ResourceManager.GetString("NotificationOpenedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not joined to this event.
        /// </summary>
        internal static string NotJoinedEvent {
            get {
                return ResourceManager.GetString("NotJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point must be between 1 and 5..
        /// </summary>
        internal static string PointInvalid {
            get {
                return ResourceManager.GetString("PointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string PresidentEmailInvalid {
            get {
                return ResourceManager.GetString("PresidentEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President email must be an edu.tr address.
        /// </summary>
        internal static string PresidentEmailMustBeEdu {
            get {
                return ResourceManager.GetString("PresidentEmailMustBeEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President email address cannot be empty.
        /// </summary>
        internal static string PresidentEmailRequired {
            get {
                return ResourceManager.GetString("PresidentEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        internal static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support email address is not configured..
        /// </summary>
        internal static string SupportEmailNotConfigured {
            get {
                return ResourceManager.GetString("SupportEmailNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unfollowed the club.
        /// </summary>
        internal static string UnfollowClubSuccess {
            get {
                return ResourceManager.GetString("UnfollowClubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is created successes..
        /// </summary>
        internal static string UniversityCreatedSuccesses {
            get {
                return ResourceManager.GetString("UniversityCreatedSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University deleted successfully..
        /// </summary>
        internal static string UniversityDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UniversityDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University not found..
        /// </summary>
        internal static string UniversityNotFound {
            get {
                return ResourceManager.GetString("UniversityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time is invalid.
        /// </summary>
        internal static string UpdateClockInvalid {
            get {
                return ResourceManager.GetString("UpdateClockInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be between 10 and 1000 characters.
        /// </summary>
        internal static string UpdateDescriptionInvalid {
            get {
                return ResourceManager.GetString("UpdateDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be later than start date.
        /// </summary>
        internal static string UpdateEndDateInvalid {
            get {
                return ResourceManager.GetString("UpdateEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be between 3 and 200 characters.
        /// </summary>
        internal static string UpdateLocationInvalid {
            get {
                return ResourceManager.GetString("UpdateLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota must be greater than 0.
        /// </summary>
        internal static string UpdateQuotaInvalid {
            get {
                return ResourceManager.GetString("UpdateQuotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be in the future.
        /// </summary>
        internal static string UpdateStartDateInvalid {
            get {
                return ResourceManager.GetString("UpdateStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event status is invalid.
        /// </summary>
        internal static string UpdateStatusInvalid {
            get {
                return ResourceManager.GetString("UpdateStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event tag is invalid.
        /// </summary>
        internal static string UpdateTagInvalid {
            get {
                return ResourceManager.GetString("UpdateTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be between 3 and 150 characters.
        /// </summary>
        internal static string UpdateTitleInvalid {
            get {
                return ResourceManager.GetString("UpdateTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must follow the club..
        /// </summary>
        internal static string UserMustFollowClub {
            get {
                return ResourceManager.GetString("UserMustFollowClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must follow the club first..
        /// </summary>
        internal static string UserNotFollowingClub {
            get {
                return ResourceManager.GetString("UserNotFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must join the event before commenting..
        /// </summary>
        internal static string UserNotJoinedEvent {
            get {
                return ResourceManager.GetString("UserNotJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been created successfully.
        /// </summary>
        internal static string UserRegisterSuccess {
            get {
                return ResourceManager.GetString("UserRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid or has expired..
        /// </summary>
        internal static string VerificationCodeInvalidOrExpired {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code has been sent to your email.
        /// </summary>
        internal static string VerificationCodeSent {
            get {
                return ResourceManager.GetString("VerificationCodeSent", resourceCulture);
            }
        }
    }
}
