//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniTrack.Application.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniTrack.Application.Common.Localization.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alreadey readed all comment..
        /// </summary>
        public static string AlreadyAllCommentReaded {
            get {
                return ResourceManager.GetString("AlreadyAllCommentReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked in to this event..
        /// </summary>
        public static string AlreadyCheckedIn {
            get {
                return ResourceManager.GetString("AlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already commented on this event..
        /// </summary>
        public static string AlreadyCommented {
            get {
                return ResourceManager.GetString("AlreadyCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already following this club.
        /// </summary>
        public static string AlreadyFollowingClub {
            get {
                return ResourceManager.GetString("AlreadyFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already joined this event.
        /// </summary>
        public static string AlreadyJoinedEvent {
            get {
                return ResourceManager.GetString("AlreadyJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already liked this comment..
        /// </summary>
        public static string AlreadyLiked {
            get {
                return ResourceManager.GetString("AlreadyLiked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already reviewed..
        /// </summary>
        public static string AlreadyReviewed {
            get {
                return ResourceManager.GetString("AlreadyReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully checked in to the event..
        /// </summary>
        public static string CheckInSuccess {
            get {
                return ResourceManager.GetString("CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club already banned.
        /// </summary>
        public static string ClubAlreadyBanned {
            get {
                return ResourceManager.GetString("ClubAlreadyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club already verified.
        /// </summary>
        public static string ClubAlreadyVerified {
            get {
                return ResourceManager.GetString("ClubAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club is created successes..
        /// </summary>
        public static string ClubCreatedSuccess {
            get {
                return ResourceManager.GetString("ClubCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use.
        /// </summary>
        public static string ClubEmailAlreadyExists {
            get {
                return ResourceManager.GetString("ClubEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clubs found..
        /// </summary>
        public static string ClubFansNotFound {
            get {
                return ResourceManager.GetString("ClubFansNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club is not found..
        /// </summary>
        public static string ClubNotFound {
            get {
                return ResourceManager.GetString("ClubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No club found with this email address..
        /// </summary>
        public static string ClubNotFoundByEmail {
            get {
                return ResourceManager.GetString("ClubNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClubNotVerified.
        /// </summary>
        public static string ClubNotVerified {
            get {
                return ResourceManager.GetString("ClubNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club password has been updated successfully..
        /// </summary>
        public static string ClubPasswordResetSuccess {
            get {
                return ResourceManager.GetString("ClubPasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during club registration.
        /// </summary>
        public static string ClubRegisterFailed {
            get {
                return ResourceManager.GetString("ClubRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid club tag.
        /// </summary>
        public static string ClubTagInvalid {
            get {
                return ResourceManager.GetString("ClubTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team created successfully..
        /// </summary>
        public static string ClubTeamCreatedSuccess {
            get {
                return ResourceManager.GetString("ClubTeamCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team deleted successfully..
        /// </summary>
        public static string ClubTeamDeletedSuccess {
            get {
                return ResourceManager.GetString("ClubTeamDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club team not found or you are not authorized to delete it..
        /// </summary>
        public static string ClubTeamNotFound {
            get {
                return ResourceManager.GetString("ClubTeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The club has been successfully verified..
        /// </summary>
        public static string ClubVerifiedSuccess {
            get {
                return ResourceManager.GetString("ClubVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment added successfully..
        /// </summary>
        public static string CommentCreatedSuccess {
            get {
                return ResourceManager.GetString("CommentCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment deleted successfully..
        /// </summary>
        public static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment not found..
        /// </summary>
        public static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully. We will get back to you as soon as possible..
        /// </summary>
        public static string ContactMessageSent {
            get {
                return ResourceManager.GetString("ContactMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new event..
        /// </summary>
        public static string CreatedNewEvent {
            get {
                return ResourceManager.GetString("CreatedNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password you entered is incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your current password to change it..
        /// </summary>
        public static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A department with this name already exists..
        /// </summary>
        public static string DepartmentAlreadyExists {
            get {
                return ResourceManager.GetString("DepartmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department created successfully..
        /// </summary>
        public static string DepartmentCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is deleted successfully..
        /// </summary>
        public static string DepartmentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department not found..
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event already ended..
        /// </summary>
        public static string EventAlreadyEnded {
            get {
                return ResourceManager.GetString("EventAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already reported this event..
        /// </summary>
        public static string EventAlreadyReported {
            get {
                return ResourceManager.GetString("EventAlreadyReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event city is required..
        /// </summary>
        public static string EventCityRequired {
            get {
                return ResourceManager.GetString("EventCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time/clock is required..
        /// </summary>
        public static string EventClockRequired {
            get {
                return ResourceManager.GetString("EventClockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event club is required..
        /// </summary>
        public static string EventClubRequired {
            get {
                return ResourceManager.GetString("EventClubRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new event has been created..
        /// </summary>
        public static string EventCreatedNotification {
            get {
                return ResourceManager.GetString("EventCreatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event created successfully..
        /// </summary>
        public static string EventCreatedSuccess {
            get {
                return ResourceManager.GetString("EventCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Creation Failed..
        /// </summary>
        public static string EventCreationFailed {
            get {
                return ResourceManager.GetString("EventCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; event has been deleted..
        /// </summary>
        public static string EventDeletedNotification {
            get {
                return ResourceManager.GetString("EventDeletedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully..
        /// </summary>
        public static string EventDeletedSuccess {
            get {
                return ResourceManager.GetString("EventDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description is required..
        /// </summary>
        public static string EventDescriptionRequired {
            get {
                return ResourceManager.GetString("EventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after the start date..
        /// </summary>
        public static string EventEndDateInvalid {
            get {
                return ResourceManager.GetString("EventEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event has already ended.
        /// </summary>
        public static string EventExpired {
            get {
                return ResourceManager.GetString("EventExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required for deletion..
        /// </summary>
        public static string EventIdRequired {
            get {
                return ResourceManager.GetString("EventIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is deleted..
        /// </summary>
        public static string EventIsDeleted {
            get {
                return ResourceManager.GetString("EventIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event is updated.
        /// </summary>
        public static string EventIsUpdated {
            get {
                return ResourceManager.GetString("EventIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully joined the event.
        /// </summary>
        public static string EventJoinSuccess {
            get {
                return ResourceManager.GetString("EventJoinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully left the event.
        /// </summary>
        public static string EventLeftSuccess {
            get {
                return ResourceManager.GetString("EventLeftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event location is required..
        /// </summary>
        public static string EventLocationRequired {
            get {
                return ResourceManager.GetString("EventLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has not ended yet..
        /// </summary>
        public static string EventNotFinished {
            get {
                return ResourceManager.GetString("EventNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        public static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were made to the event.
        /// </summary>
        public static string EventNotModified {
            get {
                return ResourceManager.GetString("EventNotModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event quota is full.
        /// </summary>
        public static string EventQuotaFull {
            get {
                return ResourceManager.GetString("EventQuotaFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event quota must be a positive number..
        /// </summary>
        public static string EventQuotaInvalid {
            get {
                return ResourceManager.GetString("EventQuotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be in the past or invalid..
        /// </summary>
        public static string EventStartDateInvalid {
            get {
                return ResourceManager.GetString("EventStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event status provided..
        /// </summary>
        public static string EventStatusInvalid {
            get {
                return ResourceManager.GetString("EventStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one valid event tag is required..
        /// </summary>
        public static string EventTagInvalid {
            get {
                return ResourceManager.GetString("EventTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time invalied.
        /// </summary>
        public static string EventTimeInvalied {
            get {
                return ResourceManager.GetString("EventTimeInvalied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title is required..
        /// </summary>
        public static string EventTitleRequired {
            get {
                return ResourceManager.GetString("EventTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is only available to students of the same university.
        /// </summary>
        public static string EventUniversityOnly {
            get {
                return ResourceManager.GetString("EventUniversityOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event university is required..
        /// </summary>
        public static string EventUniversityRequired {
            get {
                return ResourceManager.GetString("EventUniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &apos;{0}&apos; you joined has been updated..
        /// </summary>
        public static string EventUpdatedNotification {
            get {
                return ResourceManager.GetString("EventUpdatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated successfully..
        /// </summary>
        public static string EventUpdatedSuccess {
            get {
                return ResourceManager.GetString("EventUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club followed successfully.
        /// </summary>
        public static string FollowClubSuccess {
            get {
                return ResourceManager.GetString("FollowClubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event loaded successfully..
        /// </summary>
        public static string GetEventSuccesses {
            get {
                return ResourceManager.GetString("GetEventSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Sheet Creation Failed..
        /// </summary>
        public static string GoogleSheetCreationFailed {
            get {
                return ResourceManager.GetString("GoogleSheetCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event’s Google Sheets spreadsheet ID could not be found..
        /// </summary>
        public static string GoogleSheetsTableNotFound {
            get {
                return ResourceManager.GetString("GoogleSheetsTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Image not found..
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalide request..
        /// </summary>
        public static string InvalideRequest {
            get {
                return ResourceManager.GetString("InvalideRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid or has expired..
        /// </summary>
        public static string InvalidOrExpiredCode {
            get {
                return ResourceManager.GetString("InvalidOrExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tag selection.
        /// </summary>
        public static string InvalidTag {
            get {
                return ResourceManager.GetString("InvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked as reviewed..
        /// </summary>
        public static string MarkedAsReviewed {
            get {
                return ResourceManager.GetString("MarkedAsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at most 100 characters..
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 2 characters..
        /// </summary>
        public static string MinLength2 {
            get {
                return ResourceManager.GetString("MinLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be the same as the current password..
        /// </summary>
        public static string NewPasswordCannotBeSameAsOld {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeSameAsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password..
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no complaints yet..
        /// </summary>
        public static string NoComplaintsAtTheMoment {
            get {
                return ResourceManager.GetString("NoComplaintsAtTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not following this club.
        /// </summary>
        public static string NotFollowingClub {
            get {
                return ResourceManager.GetString("NotFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are already closed for this club..
        /// </summary>
        public static string NotificationAlreadyClosed {
            get {
                return ResourceManager.GetString("NotificationAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are already enabled for this club..
        /// </summary>
        public static string NotificationAlreadyOpened {
            get {
                return ResourceManager.GetString("NotificationAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club notifications have been successfully closed..
        /// </summary>
        public static string NotificationClosedSuccess {
            get {
                return ResourceManager.GetString("NotificationClosedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification not found.
        /// </summary>
        public static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club notifications have been successfully enabled..
        /// </summary>
        public static string NotificationOpenedSuccess {
            get {
                return ResourceManager.GetString("NotificationOpenedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification is send successes..
        /// </summary>
        public static string NotificationSendSuccess {
            get {
                return ResourceManager.GetString("NotificationSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not joined to this event.
        /// </summary>
        public static string NotJoinedEvent {
            get {
                return ResourceManager.GetString("NotJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationFailed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful..
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpportunityNotFound.
        /// </summary>
        public static string OpportunityNotFound {
            get {
                return ResourceManager.GetString("OpportunityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point must be between 1 and 5..
        /// </summary>
        public static string PointInvalid {
            get {
                return ResourceManager.GetString("PointInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string PresidentEmailInvalid {
            get {
                return ResourceManager.GetString("PresidentEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President email must be an edu.tr address.
        /// </summary>
        public static string PresidentEmailMustBeEdu {
            get {
                return ResourceManager.GetString("PresidentEmailMustBeEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President email address cannot be empty.
        /// </summary>
        public static string PresidentEmailRequired {
            get {
                return ResourceManager.GetString("PresidentEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report not found..
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support email address is not configured..
        /// </summary>
        public static string SupportEmailNotConfigured {
            get {
                return ResourceManager.GetString("SupportEmailNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully unfollowed the club.
        /// </summary>
        public static string UnfollowClubSuccess {
            get {
                return ResourceManager.GetString("UnfollowClubSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is created successes..
        /// </summary>
        public static string UniversityCreatedSuccesses {
            get {
                return ResourceManager.GetString("UniversityCreatedSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University deleted successfully..
        /// </summary>
        public static string UniversityDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UniversityDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University not found..
        /// </summary>
        public static string UniversityNotFound {
            get {
                return ResourceManager.GetString("UniversityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time is invalid.
        /// </summary>
        public static string UpdateClockInvalid {
            get {
                return ResourceManager.GetString("UpdateClockInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be between 10 and 1000 characters.
        /// </summary>
        public static string UpdateDescriptionInvalid {
            get {
                return ResourceManager.GetString("UpdateDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be later than start date.
        /// </summary>
        public static string UpdateEndDateInvalid {
            get {
                return ResourceManager.GetString("UpdateEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location must be between 3 and 200 characters.
        /// </summary>
        public static string UpdateLocationInvalid {
            get {
                return ResourceManager.GetString("UpdateLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota must be greater than 0.
        /// </summary>
        public static string UpdateQuotaInvalid {
            get {
                return ResourceManager.GetString("UpdateQuotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be in the future.
        /// </summary>
        public static string UpdateStartDateInvalid {
            get {
                return ResourceManager.GetString("UpdateStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event status is invalid.
        /// </summary>
        public static string UpdateStatusInvalid {
            get {
                return ResourceManager.GetString("UpdateStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event tag is invalid.
        /// </summary>
        public static string UpdateTagInvalid {
            get {
                return ResourceManager.GetString("UpdateTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be between 3 and 150 characters.
        /// </summary>
        public static string UpdateTitleInvalid {
            get {
                return ResourceManager.GetString("UpdateTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already verified.
        /// </summary>
        public static string UserAlreadyVerified {
            get {
                return ResourceManager.GetString("UserAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must follow the club..
        /// </summary>
        public static string UserMustFollowClub {
            get {
                return ResourceManager.GetString("UserMustFollowClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must follow the club first..
        /// </summary>
        public static string UserNotFollowingClub {
            get {
                return ResourceManager.GetString("UserNotFollowingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must join the event before commenting..
        /// </summary>
        public static string UserNotJoinedEvent {
            get {
                return ResourceManager.GetString("UserNotJoinedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been created successfully.
        /// </summary>
        public static string UserRegisterSuccess {
            get {
                return ResourceManager.GetString("UserRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User verified success.
        /// </summary>
        public static string UserVerifiedSuccess {
            get {
                return ResourceManager.GetString("UserVerifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid or has expired..
        /// </summary>
        public static string VerificationCodeInvalidOrExpired {
            get {
                return ResourceManager.GetString("VerificationCodeInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code resent success.
        /// </summary>
        public static string VerificationCodeResentSuccess {
            get {
                return ResourceManager.GetString("VerificationCodeResentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code has been sent to your email.
        /// </summary>
        public static string VerificationCodeSent {
            get {
                return ResourceManager.GetString("VerificationCodeSent", resourceCulture);
            }
        }
    }
}
