//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniTrack.Application.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniTrack.Application.Common.Localization.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked in to this event..
        /// </summary>
        internal static string AlreadyCheckedIn {
            get {
                return ResourceManager.GetString("AlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully checked in to the event..
        /// </summary>
        internal static string CheckInSuccess {
            get {
                return ResourceManager.GetString("CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event city is required..
        /// </summary>
        internal static string EventCityRequired {
            get {
                return ResourceManager.GetString("EventCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event time/clock is required..
        /// </summary>
        internal static string EventClockRequired {
            get {
                return ResourceManager.GetString("EventClockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event club is required..
        /// </summary>
        internal static string EventClubRequired {
            get {
                return ResourceManager.GetString("EventClubRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new event has been created..
        /// </summary>
        internal static string EventCreatedNotification {
            get {
                return ResourceManager.GetString("EventCreatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event created successfully..
        /// </summary>
        internal static string EventCreatedSuccess {
            get {
                return ResourceManager.GetString("EventCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; event has been deleted..
        /// </summary>
        internal static string EventDeletedNotification {
            get {
                return ResourceManager.GetString("EventDeletedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully..
        /// </summary>
        internal static string EventDeletedSuccess {
            get {
                return ResourceManager.GetString("EventDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description is required..
        /// </summary>
        internal static string EventDescriptionRequired {
            get {
                return ResourceManager.GetString("EventDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after the start date..
        /// </summary>
        internal static string EventEndDateInvalid {
            get {
                return ResourceManager.GetString("EventEndDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name is required for deletion..
        /// </summary>
        internal static string EventIdRequired {
            get {
                return ResourceManager.GetString("EventIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event location is required..
        /// </summary>
        internal static string EventLocationRequired {
            get {
                return ResourceManager.GetString("EventLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not found..
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event quota must be a positive number..
        /// </summary>
        internal static string EventQuotaInvalid {
            get {
                return ResourceManager.GetString("EventQuotaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be in the past or invalid..
        /// </summary>
        internal static string EventStartDateInvalid {
            get {
                return ResourceManager.GetString("EventStartDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event status provided..
        /// </summary>
        internal static string EventStatusInvalid {
            get {
                return ResourceManager.GetString("EventStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one valid event tag is required..
        /// </summary>
        internal static string EventTagInvalid {
            get {
                return ResourceManager.GetString("EventTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event title is required..
        /// </summary>
        internal static string EventTitleRequired {
            get {
                return ResourceManager.GetString("EventTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event university is required..
        /// </summary>
        internal static string EventUniversityRequired {
            get {
                return ResourceManager.GetString("EventUniversityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event &apos;{0}&apos; you joined has been updated..
        /// </summary>
        internal static string EventUpdatedNotification {
            get {
                return ResourceManager.GetString("EventUpdatedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event updated successfully..
        /// </summary>
        internal static string EventUpdatedSuccess {
            get {
                return ResourceManager.GetString("EventUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
    }
}
